language: ruby
rvm:
  - "2.7.0"
  - "2.6.5"
  - "2.5.7"
  - "2.4.9"
  - "2.3.1"
  - "2.2.5"
  - "2.1.9"
  - "2.0.0"
  - "1.9.3"
  - "1.8.7"
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rack-1.x
before_install:
  - gem update bundler
matrix:
  exclude:
    - rvm: 2.7.0
      gemfile: gemfiles/Gemfile.rack-1.x
    - rvm: 2.1.9
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 1.8.7
      gemfile: Gemfile
